AllCops:
  Exclude:
    - bin/*
    - vendor/**/*
    - pkg/**/*
  TargetRubyVersion: '2.5'
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
 # Removing Blocks Cop for RSpec
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
 # Removing Indentation Cop for RSpec
Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*'
    - 'config/environments/**/*'
Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'spec/**/*'
