version: '3.8'

services:
  solr:
    image: solr:${SOLR_VERSION:-9.7.0}-slim
    ports:
      - "8983:8983"
    volumes:
      - solr_single_data:/var/solr
    healthcheck:
      test: |
        curl -sf 'http://localhost:8983/solr/admin/cores?action=STATUS' | grep -q '"status":{' \
        && curl -sf 'http://localhost:8983/solr/admin/info/system' | grep -q '"status":"ok"' \
        && curl -sf 'http://localhost:8983/solr/admin/ping?wt=json' | grep -q '"status":"OK"'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  solr_single_data:
