version: '3.8'

services:
  solr:
    image: solr:9.7.0-slim
    ports:
      - "8983:8983"
    volumes:
      - solr_single_data:/var/solr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  solr_single_data:
