---
name: Tests
'on': [push]

env:
  SOLR_URL: http://localhost:8983/solr/test-core

jobs:
  rspec_single:
    name: Rspec on Ruby ${{ matrix.ruby }} with Solr ${{ matrix.solr }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.2']
        solr: ['8.11.2', '9.7.0']
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2
        env:
          SOLR_VERSION: ${{ matrix.solr }}
        with:
          compose-file: docker-compose.single.yml

      - name: Prepare default configset
        run: |
          docker exec -u 0 solrb-solr-1 sh -c \
          "mkdir -p /var/solr/data/configsets && cp -R /opt/solr/server/solr/configsets/_default /var/solr/data/configsets/ \
          && chown -R solr:solr /var/solr/data/configsets"

      - name: Create a test core
        run: |
          curl 'http://localhost:8983/solr/admin/cores?action=CREATE&name=test-core&configSet=_default'

      - name: Disable field type guessing
        run: |
          curl http://localhost:8983/solr/test-core/config -d '{"set-user-property": {"update.autoCreateFields":"false"}}'

      - name: Rspec
        run: bundle exec rspec --format progress --tag ~installation:master-replica --tag ~installation:cloud
