---
name: Tests
'on': [push]

env:
  SOLR_URL: http://localhost:8983/solr/test-core

jobs:
  rspec:
    name: Rspec on Ruby ${{ matrix.ruby }} with Solr ${{ matrix.solr }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.2']
        solr: ['7.4.0', '8.11.2']
    services:
      solr:
        image: solr:${{ matrix.solr }}
        ports:
          - 8983:8983
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Create a test core
        run: |
          curl 'http://localhost:8983/solr/admin/cores?action=CREATE&name=test-core&configSet=_default'

      - name: Disable field type guessing
        run: |
          curl http://localhost:8983/solr/test-core/config -d '{"set-user-property": {"update.autoCreateFields":"false"}}'

      - name: Rspec
        run: bundle exec rspec --format progress
